/**
 * Dev-only fixture generator — NOT wired into `prisma db seed`, which
 * deliberately leaves the board empty.
 *
 *   pnpm tsx scripts/seed-demo.ts 60
 *
 * Inserts N published listings with descending bids so pagination, the takeover
 * freeze and the rank maths have something to chew on.
 */
import "dotenv/config";
import { db } from "../src/lib/db";
import { IdentityType, ListingStatus } from "../src/generated/prisma/enums";

const count = Number.parseInt(process.argv[2] ?? "60", 10);

async function main() {
  const now = Date.now();

  for (let i = 0; i < count; i++) {
    const host = `demo-${String(i + 1).padStart(3, "0")}.test`;
    await db.listing.upsert({
      where: { identityKey: `website:${host}` },
      update: {},
      create: {
        identityType: IdentityType.WEBSITE,
        identityKey: `website:${host}`,
        sourceUrl: `https://${host}/`,
        displayName: `Demo Product ${i + 1}`,
        description: `Placeholder listing #${i + 1}, generated by scripts/seed-demo.ts to exercise pagination and ranking.`,
        status: ListingStatus.PUBLISHED,
        // Descending bids, each a whole dollar, starting well below the real rows.
        amountCents: (count - i) * 100,
        clickCount: (i * 7) % 40,
        rankedAt: new Date(now - i * 60_000),
      },
    });
  }

  const total = await db.listing.count({ where: { status: ListingStatus.PUBLISHED } });
  console.log(`Inserted ${count} demo listings. Board now has ${total} published rows.`);
  await db.$disconnect();
}

void main();
